### ISSUE TITLE
Pulse oximeter/photoplethysmography

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/FIU-CIS#14]
# Technology name
Pulse oximeter/photoplethysmograph

# Link to website
- [Photoplethysmograph Transducer for MRI](https://www.biopac.com/product/photoplethysmograph-transducer-for-mri/)
- [Photo Plethysmogram Amplifier for MRI](https://www.biopac.com/product/pulse-plethysmogram-amplifier-for-mri/)

# Cost information
The transducer is $265.00, while the amplifier requires users to log in to view cost information.

# Funding source
The CIS.

# Additional information (optional)
While we have ECG, apparently PPG is better for MRI. It's not just better for denoising fMRI data, but it also appears to be less impacted by MR pulse artifacts.

I'm pinging @ericamusser, given that she's the person at the CIS who knows the most about physio.

# Requesters
@tsalo

**Comment by ericamusser** [comment]
We HAVE PPG, I think. I just don't use it for my work.

**Comment by tsalo** [comment]
We do? I thought we were using all of the available amplifiers already? Are there any other amplifier boxes that aren't in use?

**Comment by ericamusser** [comment]
[cid:f995c07b-f18d-4fa6-9ca5-d2686ad4f2db]

*************************************************************************************

Erica D. Musser, Ph.D.

Associate Professor of Psychology (Clinical Science)

Licensed Clinical Psychologist (PY9825)

Center for Children and Families<http://www.ccf.fiu.edu/>, an FIU Preeminent Program<https://beyondpossible.fiu.edu/preeminent-programs/>

11200 SW 8th St.

AHC 4 | Room 455

Miami, FL 33199

Phone: 305.348.1034

Fax: 305.348.3646

Email: emusser@fiu.edu

Website: http://emusse2.wixsite.com/abc-erica-lab


*Pronouns: she, her, hers (What's This?<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.glsen.org_sites_default_files_GLSEN-2520Pronouns-2520Resource.pdf&d=DwMFaQ&c=lhMMI368wojMYNABHh1gQQ&r=mdBigafsFYz1Z5m9ZPNAyQ&m=ON8C3Cffdm4kU6f6xDKjgeQ5Da3XUwkQkJx0exnfOS8&s=oslk2C9KFp9wmnRhJTqc-eU_u5cQfJkdrysgDj4DzRk&e=>)


Confidentiality: Please be advised that we cannot guarantee the confidentiality of information sent via email. The information transmitted in this email is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination, or other use of or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this email in error, please contact the sender and delete the material from any computer.


________________________________
